services :
  mariadb :
    image : mariadb
    environment :
      - MARIADB_ROOT_PASSWORD=$(MARIADB_ROOT_PASSWORD)
      - MARIADB_USER=$(MARIADB_USER)
      - MARIADB_PASSWORD=$(MARIADB_PASSWORD)
      - MARIADB_DATABASE=$(MARIADB_DATABASE)
  monapache:
    image: lenabct/monapache
    ports:
      - 8000:80
  monubuntu:
    image: lenabct/monubuntu
  phpmyadmin: 
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80