services :
  mariadb :
    image : mariadb
    environment :
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=oui
      - MARIADB_PASSWORD=oui
      - MARIADB_DATABASE=jeanted
    ports : 
      - 3306:3306
  monapache:
    image: lenabct/monapache
    ports:
      - 80:80
  monubuntu:
    image: lenabct/monubuntu
  phpmyadmin: 
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80